name: PowerShell script
inputs:
  tenants:
    descripton: Specifies in which tenant(s) the app should be installed
    required: true
    default: ''
  environments:
    description: Specifies in which environment(s) the app should be deployed (O/T/A)
    required: true
    default: ''    
  azureSAS:
    description: Specifies the Azure SAS Token
    required: true
    default: ''   
  repoName:
    description: Specifies the repository name
    required: true
    default: ''   
  source:
    description: Specifies if the build was created in the Acceptance or Development process (A or O)
    required: false
    default: 'T'  
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/Deploy-App.ps1 -tenants '${{ inputs.tenants }}' -environments '${{ inputs.environments }}' -azureSAS '$({ inputs.azureSAS})' -repoName '$({ inputs.repoName})'
      id: deployapp
      shell: PowerShell
branding:
  icon: terminal
  color: blue