name: PowerShell script
inputs:
  project:
    description: Project folder
    required: false
    default: '.'
outputs:
  SettingsJson:
    description: Settings in compressed Json format
    value: ${{ steps.readsettings.outputs.SettingsJson }}
  GitHubRunnerJson:
    description: GitHubRunner in compressed Json format
    value: ${{ steps.readsettings.outputs.GitHubRunnerJson }}
  ProjectsJson:
    description: Projects in compressed Json format
    value: ${{ steps.readsettings.outputs.ProjectsJson }}
  ProjectCount:
    description: Number of projects in array
    value: ${{ steps.readsettings.outputs.ProjectCount }}
  EnvironmentsJson:
    description: Environments in compressed Json format
    value: ${{ steps.readsettings.outputs.EnvironmentsJson }}
  EnvironmentCount:
    description: Number of environments in array
    value: ${{ steps.readsettings.outputs.EnvironmentCount }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/ReadSettings.ps1 -project '${{ inputs.project }}'
      id: readsettings
      shell: PowerShell
branding:
  icon: terminal
  color: blue